<?php

/**
 * PluginLrSubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLrSubscriberTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLrSubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLrSubscriber');
    }
}