<?php

/**
 * PluginLrNewsletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLrNewsletterTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLrNewsletterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLrNewsletter');
    }
}