<?php

/**
 * PluginLrArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLrArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLrArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLrArticle');
    }
}